theme: jekyll-theme-midnight
title: atomtr's homepage
description: Hoh
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://atom-tr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
